"""add_meta_connections_table

Revision ID: 604cd7392dc3
Revises: 001
Create Date: 2026-01-26 22:14:36.236062+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '604cd7392dc3'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad_groups', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'ACTIVE', 'PAUSED', 'DELETED', name='adstatusenum'),
               nullable=False,
               existing_server_default=sa.text("'DRAFT'::adstatusenum"))
    op.alter_column('ad_groups', 'bid_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'AUTO'::character varying"))
    op.alter_column('ad_groups', 'impressions',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ad_groups', 'clicks',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ad_groups', 'engagements',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ad_groups', 'spend_micros',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ad_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ad_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('ad_groups_campaign_id_fkey', 'ad_groups', type_='foreignkey')
    op.create_foreign_key(None, 'ad_groups', 'campaigns', ['campaign_id'], ['id'])
    op.alter_column('ads', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'ACTIVE', 'PAUSED', 'DELETED', name='adstatusenum'),
               nullable=False,
               existing_server_default=sa.text("'DRAFT'::adstatusenum"))
    op.alter_column('ads', 'impressions',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ads', 'clicks',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ads', 'engagements',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ads', 'spend_micros',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('ads_ad_group_id_fkey', 'ads', type_='foreignkey')
    op.create_foreign_key(None, 'ads', 'ad_groups', ['ad_group_id'], ['id'])
    op.alter_column('analytics_cache', 'impressions',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('analytics_cache', 'engagements',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('analytics_cache', 'likes',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('analytics_cache', 'retweets',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('analytics_cache', 'replies',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('analytics_cache', 'profile_visits',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('analytics_cache', 'followers_gained',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('analytics_cache', 'followers_lost',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('analytics_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('analytics_cache_user_id_fkey', 'analytics_cache', type_='foreignkey')
    op.create_foreign_key(None, 'analytics_cache', 'users', ['user_id'], ['id'])
    op.alter_column('campaigns', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'DELETED', name='campaignstatusenum'),
               nullable=False,
               existing_server_default=sa.text("'DRAFT'::campaignstatusenum"))
    op.alter_column('campaigns', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('campaigns', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('campaigns', 'impressions',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('campaigns', 'clicks',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('campaigns', 'engagements',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('campaigns', 'spend_micros',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('campaigns_user_id_fkey', 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'users', ['user_id'], ['id'])
    op.alter_column('oauth_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_states', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('oauth_states_user_id_fkey', 'oauth_states', type_='foreignkey')
    op.create_foreign_key(None, 'oauth_states', 'users', ['user_id'], ['id'])
    op.alter_column('user_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'last_activity',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('user_sessions_user_id_fkey', 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'followers_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'following_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'tweet_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'listed_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'protected',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'protected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'listed_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'tweet_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'following_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'followers_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key('user_sessions_user_id_fkey', 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_sessions', 'last_activity',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'oauth_states', type_='foreignkey')
    op.create_foreign_key('oauth_states_user_id_fkey', 'oauth_states', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('oauth_states', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('oauth_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key('campaigns_user_id_fkey', 'campaigns', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'spend_micros',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('campaigns', 'engagements',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('campaigns', 'clicks',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('campaigns', 'impressions',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('campaigns', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('campaigns', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('campaigns', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'DELETED', name='campaignstatusenum'),
               nullable=True,
               existing_server_default=sa.text("'DRAFT'::campaignstatusenum"))
    op.drop_constraint(None, 'analytics_cache', type_='foreignkey')
    op.create_foreign_key('analytics_cache_user_id_fkey', 'analytics_cache', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('analytics_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('analytics_cache', 'followers_lost',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('analytics_cache', 'followers_gained',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('analytics_cache', 'profile_visits',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('analytics_cache', 'replies',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('analytics_cache', 'retweets',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('analytics_cache', 'likes',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('analytics_cache', 'engagements',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('analytics_cache', 'impressions',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.drop_constraint(None, 'ads', type_='foreignkey')
    op.create_foreign_key('ads_ad_group_id_fkey', 'ads', 'ad_groups', ['ad_group_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ads', 'spend_micros',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ads', 'engagements',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ads', 'clicks',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ads', 'impressions',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ads', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'ACTIVE', 'PAUSED', 'DELETED', name='adstatusenum'),
               nullable=True,
               existing_server_default=sa.text("'DRAFT'::adstatusenum"))
    op.drop_constraint(None, 'ad_groups', type_='foreignkey')
    op.create_foreign_key('ad_groups_campaign_id_fkey', 'ad_groups', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ad_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ad_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ad_groups', 'spend_micros',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ad_groups', 'engagements',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ad_groups', 'clicks',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ad_groups', 'impressions',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ad_groups', 'bid_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'AUTO'::character varying"))
    op.alter_column('ad_groups', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'ACTIVE', 'PAUSED', 'DELETED', name='adstatusenum'),
               nullable=True,
               existing_server_default=sa.text("'DRAFT'::adstatusenum"))
    # ### end Alembic commands ###
